### ISSUE TITLE
Latest runtime download

### ISSUE THREAD

**Issue by goldytech** [DibranMulder/azure-functions-v2-dependency-injection#3]
Hi,
You mentioned that to run this project you required runtime version `2.0.1-beta.36` or higher and runtime `2.0.12050.0`
 How can I install the runtime from https://github.com/Azure/azure-functions-host/releases
Using this https://github.com/Azure/azure-functions-core-tools
doesn't install the latest runtime. It installs `2.0.11776.0`

Please help.

**Comment by DibranMulder** [comment]
If you're using Visual Studio just update to the latest version
