### ISSUE TITLE
Deploy To Azure

### ISSUE THREAD

**Issue by kkman021** [DibranMulder/azure-functions-v2-dependency-injection#4]
Hi,
I study your code , it's works on my develope env. which below:

 - Visual Studio 2017  => 15.8.4
 - Azure Functions Core Tools =>  2.0.1-beta.39
 - Function Runtime Version =>  2.0.12095.0

NuGet Package just follow the sample code,

 - Microsoft.NET.Sdk.Functions (1.0.19)
 - Microsoft.Azure.WebJobs (3.0.0-beta8)
 - Microsoft.Extensions.DependencyInjection.Abstractions (2.1.1)

When i deploy to azure withing VS2017, i call the api/demo , i get http status code :500 .

Application Insight show the error:

Error indexing method 'DemoFunction.Run' Cannot bind parameter 'demoService' to type IDemoService. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

Do you know , what the reason ?

About the azure setting
 - Run time version : 2.0.12095.0
 - FUNCTIONS_EXTENSION_VERSION : ~2

Thanks for your time.

**Comment by scarbon** [comment]
I'm getting the same issue, haven't been able to work it out yet

**Comment by kkman021** [comment]
@scarbon  there's a workable soluction in [this comment](https://github.com/Azure/azure-webjobs-sdk/issues/1865#issuecomment-420752077),

It's works for me.
